### ISSUE TITLE
blend-basic won't load

### ISSUE THREAD

**Issue by randompast** [stackgl/webgl-workshop#56]
https://github.com/stackgl/webgl-workshop/blob/master/exercises/blend-basics/submission/index.js#L1

Replacing line 1 with the following solved my problem:
var setup = require('./setup')

**Comment by mreinstein** [comment]
I'm having this problem too

<img width="893" alt="screen shot 2015-10-14 at 11 28 27 am" src="https://cloud.githubusercontent.com/assets/718067/10493566/b770b79c-7266-11e5-9e4c-4373a0fee996.png">
