### ISSUE TITLE
3d-cull-face rejects correct solution

### ISSUE THREAD

**Issue by RGBboy** [stackgl/webgl-workshop#60]
Just found a bug with the 3d-cull-face lesson where it will not accept my answer even if I copy and paste the solution. I'm pretty sure it has something to do with passing Date.now() to the drawIt function. If you replace the Date.now() with a fixed value it works. There must be a significant enough delay between calling the solution and the given answer to make Date.now() return different times.

**Comment by mreinstein** [comment]
+1 having the same problem
